@startuml
class Video
class Category
class CategoryType

class Video {
    -videoId: long
    -videoURL: String
    -name: String
    -date: date
    -length: int
    -preview: Base64
    -categories: Set
}

class Category {
    -categoryId: long
    -name: String
    -categoryTypeId: long
}

class CategoryType {
    -categoryTypeId: long
    -name: String
}

@enduml