-- import.sql

-- CATEGORY_TYPE
INSERT INTO CATEGORY_TYPE (CATEGORY_TYPE_ID, NAME) VALUES (1, 'majors');
INSERT INTO CATEGORY_TYPE (CATEGORY_TYPE_ID, NAME) VALUES (2, 'industry');
INSERT INTO CATEGORY_TYPE (CATEGORY_TYPE_ID, NAME) VALUES (3, 'company size');


-- CATEGORY
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CATEGORY_TYPE_ID) VALUES (1, 'Accounting', 1);
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CATEGORY_TYPE_ID) VALUES (2, 'Marketing', 1);
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CATEGORY_TYPE_ID) VALUES (3, 'Computer and IT systems', 1);
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CATEGORY_TYPE_ID) VALUES (4, 'Aviation', 2);
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CATEGORY_TYPE_ID) VALUES (5, 'IT and Telecom', 2);
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CATEGORY_TYPE_ID) VALUES (6, 'Healthcare', 2);
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CATEGORY_TYPE_ID) VALUES (7, 'Micro-enterprises', 3);
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CATEGORY_TYPE_ID) VALUES (8, 'Small enterprises', 3);
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CATEGORY_TYPE_ID) VALUES (9, 'Medium-sized enterprises', 3);
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CATEGORY_TYPE_ID) VALUES (10, 'Large enterprises', 3);
--
---- VIDEO
--INSERT INTO VIDEO (VIDEO_URL, NAME) VALUES ('www.youtube.com/111', 'Test video 1...');
